name: EntityEdit
main: com.stefensharkey.entityedit.EntityEdit
version: ${project.version}
author: Stefenatefun

commands:
  entityedit:
    description: See EntityEdit help page.
    aliases: [ee]
    permission: entityedit.help

permissions:
  entityedit.*:
    description: Gives access to all EntityEdit permissions.
    children:
      entityedit.help: true
