name: EntityEdit
main: com.stefensharkey.entityedit.EntityEdit
version: ${project.version}
author: Stefenatefun
softdepend: [TagAPI]

commands:
  entityedit:
    description: See EntityEdit help page.
    aliases: [ee]
  entityedit armor:
    description: Sets the armor of the entity.
    permission: entityedit.armor
  entityedit copy:
    description: Copies the entity into the clipboard.
    permission: entityedit.copy
  entityedit cut:
    description: Cuts (copies and removes) the entity.
    permission: entityedit.cut
  entityedit enchant:
    description: Adds an enchantment on a piece of armor on the entity.
    permission: entityedit.enchant
  entityedit health:
    description: Sets the health of the entity.
    permission: entityedit.health
  entityedit name:
    description: Sets the name of the entity.
    permission: entityedit.name
  entityedit paste:
    description: Pastes the entity from the clipboard.
    permission: entityedit.paste

permissions:
  entityedit.*:
    description: Gives access to all EntityEdit permissions.
    children:
      entityedit.armor: true
      entityedit.copy: true
      entityedit.cut: true
      entityedit.enchant: true
      entityedit.health: true
      entityedit.name: true
      entityedit.paste: true
  entityedit.armor:
    description: Sets the armor of the entity.
    default: op
  entityedit.copy:
    description: Copies the entity into the clipboard.
    default: op
  entityedit.cut:
    description: Cuts (copies and removes) the entity.
    default: op
  entityedit.enchant:
    description: Adds an enchantment on a piece of armor on the entity.
    default: op
  entityedit.health:
    description: Sets the health of the entity.
    default: op
  entityedit.name:
    description: Sets the name of the entity.
    default: op
  entityedit paste:
    description: Pastes the entity from the clipboard.
    default: op
