name: EntityEdit
main: com.stefensharkey.entityedit.EntityEdit
version: ${project.version}
author: Stefenatefun
softdepend: [TagAPI]

commands:
  entityedit:
    description: See EntityEdit help page.
    aliases: [ee]
  entityedit armor:
    description: Sets the armor of the entity.
    permission: entityedit.armor
  entityedit health:
    description: Sets the health of the entity.
    permission: entityedit.health
  entityedit name:
    description: Sets the name of the entity.
    permission: entityedit.name

permissions:
  entityedit.*:
    description: Gives access to all EntityEdit permissions.
    children:
      entityedit.armor: true
      entityedit.health: true
      entityedit.name: true
  entityedit.armor:
    description: Sets the armor of the entity.
    default: op
  entityedit.health:
    description: Sets the health of the entity.
    default: op
  entityedit.name:
    description: Sets the name of the entity.
    default: op
